language: node_js
node_js: node

jobs:
  include:
    - stage: Test
      name: Android Build
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
        licenses:
          - 'android-sdk-license-.+'
      before_install:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
      script:
        - npm run test:js
        - npm run test:android

    - stage: Test
      name: iOS Build
      os: osx
      osx_image: xcode10.1
      script:
        - npm run test:js
        - npm run test:ios

    - stage: Deploy
      name: NPM Package
      script:
          - npm test
          - npm pack --dry-run
